youtube/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("youtubeapp.urls"), name="")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

youtubeapp/urls.py
from django.urls import path
from .import views

app_name = "youtube"

urlpatterns = [
    path("", views.index, name="home"),
    path("download/", views.download, name="download"),
    path("download/<resolution>", views.yt_download_complete, name="complete"),
]

youtubeapp/models.py
from django.db import models

# Create your models here.

youtubeapp/views.py
from django.shortcuts import render
from pytube import YouTube
import os

# Create your views here.
def index(request):
    return render(request, "index.html")

def download(request):
    global url
    url = request.GET.get("url")
    yt = YouTube(url)
    video = []
    video = yt.streams.filter(progressive=True).all()
    embed_link = url.replace("watch?v", "embed/")
    Title = yt.title
    thumbnail_url = yt.thumbnail_url
    context = {"video":video, "embed":embed_link, "title":Title, "thumbnail_url": thumbnail_url}
    
    return render(request, "download.html", context=context)

def yt_download_complete(request, resolution):
    global url 
    homedir = os.path.expanduser("~")
    dirs = homedir + "/Downloads"
    
    if request.method == "POST":
        YouTube(url).streams.get_by_resolution(resolution).download(dirs)
        return render(request, "complete.html")
    else:
        return render(request, "404.html")

youtubeapp/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Youtube Downloader</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" 
            integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" 
            crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" 
            crossorigin="anonymous">
        </script>
        {% load static %}
    </head>
    <style type="text/css">
      button {
          border: 5px red;
          border-radius: 50px
      }
      .card-title {
        color:red;
      }
      button img {
        height: auto;
        max-width: 200px;
        border-radius: 45px;
}
  </style>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary""navbar bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url "youtube:home" %}">Youtube Video Downloader</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url "youtube:home" %}">Youtube Video Downloader</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>

          {% block content %}
          {% endblock content %}

    
   </body>
</html>

youtubeapp/templates/complete.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Download Complete</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        {% load static %}
    </head>
    <style type="text/css">
        h1 {
            color:green;
            font-size:50px;
        }
        button {
            border: dotted 2px blue;
        }
        button img {
            height: auto;
            max-width: 200px;
        }
        
    </style>
    <body>
        <div class = "container">
        <center><h1>Download Complete</h1><center>
        <center><button><a href = "{% url "youtube:home" %}"> <img src= "{% static 'youtubeapp/back.png' %}"></button></center>
        </div>
   </body>
</html>
{% endblock content %}

youtubeapp/templates/download.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body>
    <div class = "card container"><center>
      <center><h2 class = "card-title" >{{title}}</h2></center>
      <div class=" embed-responsive embed-responsive-16by9">
        {% comment %} <iframe width="560" height="315" src="{{ thumbnail_url }}" frameborder="0" allowfullscreen></iframe> {% endcomment %}
        <img src="{{ thumbnail_url }}" alt="{{ embed }}">
        {% comment %}<iframe width="560" height="315" class="embed-responsive-item" src="{{ thumbnail_url }}" alt={{embed}} frameborder="0" allowfullscreen></iframe> {% endcomment %}
        <center>
        <table class="table" style="text-align":"center";>
          <thead class="thead-dark">
            <tr>
              <th scope="col">Size</th>
              <th scope="col">Quality</th>
              <th scope="col">Type</th>
              <th scope="col">Download</th>
            </tr>
          </thead>
          {% for i in video %}
          <tbody>
            <tr>
              <th>{{i.filesize}}</th>
              <td>{{i.resolution}}</td>
              <td>{{i.type}}</td>
              <td>
                <form action = "{%url "youtube:complete" i.resolution%}" method = "POST">
                  {% csrf_token %}
                  <input type = "submit" class = "btn btn-success" value = "Download">
                </form>
              </td>
            </tr>
          </tbody>
          {% endfor %}
        </table>
      
      </div>
    </div>
  </center>
</body>
{% endblock content %}

youtubeapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<html>

          <div class = "mt-5">
           <center>
            <h1>Enter YouTube Video URL</h1>
           </center>
          </div>

    <div class = "container mt-5">  
        <center>
          <form action = "download/" method = "GET">
            <div class="form-group">
              <input name = "url" type="text" class="form-control" placeholder="Input Youtube Video URL">
            </div>
            <br>
            <button type="submit"> <img src= "{% static 'youtubeapp/download.png' %}"> </button>
            {# class="btn btn-primary">Submit #}
          </form>
        </center>
    </div>
   </body>
</html>
{% endblock content %}